defaults:
  - _self_
  - experiment: null

models:
  bb_model_name: "Qwen/Qwen2.5-1.5B"
  inverse_model_name: "facebook/bart-base"
  layer_embeds_to_return: 1

training:
  dataset_name: "ag_news"
  dataset_size: 100000
  lr: 5e-5
  epochs: 30
  batch_size: 32
  max_length: 64